settings:
 granularity: 0.1
 max_tour_duration: 8.0
 min_n_stops_for_2_opt: 8
 n_cpu: 20
 n_external_zones: 13 # Liechtenstein, Büsingen, Campione d'Italia
 seed:
 sep: ';'
 write_omx: True
 write_csv: False
 write_shp: False
 weekday: True

paths:
 inputs:
  param_folder: '\parameters\'
  data_folder: '\data\'
  centroids: '${data_folder}centroidsNPVM.csv'
  params_end_tour: '${param_folder}EndTour.csv'
  params_next_stop: '${param_folder}NextStopLocation.csv'
  params_n_tours: '${param_folder}nb_tours.csv'
  params_share_active: '${param_folder}prop_active.csv'
  params_vehicle_generation: '${param_folder}VehicleGeneration.csv'
  daily_dist_per_branch_empirical_weekday: '${param_folder}dist_by_branch_weekday.csv'
  daily_dist_per_branch_empirical_full_week: '${param_folder}dist_by_branch_full_week.csv'
  tt_matrix: '${data_folder}DWV_2017_Strasse_Reisezeit_CH_7978zones.omx'
  dist_matrix: '${data_folder}DWV_2017_Strasse_Distanz_CH_7978zones.omx'
  same_zip_matrix: '${data_folder}same_zip_matrix.omx'
  zone_stats: '${data_folder}zone_stats_2021_NPVM.csv'
  prices: '${param_folder}prices_2021.csv'
  all_zones_npvm: '${data_folder}verkehrszonen_npvm_8898.csv'

 outputs:
  output_folder: '\outputs\run2021\'
  log_folder: '${output_folder}log\'
  trips_csv: '${output_folder}trips_LCV.csv'
  trips_shape: '${output_folder}trips_LCV.shp'
  trip_matrix_csv: '${output_folder}trip_matrix_LCV.csv'
  trip_matrix_omx: '${output_folder}trip_matrix_LCV.omx'
  daily_dist_per_branch_csv: '${output_folder}daily_dist_per_branch.csv'

expected_fields:
 centroids:
  - 'zone_id'
  - 'x_coord'
  - 'y_coord'
 params_correction:
  - 'Branch'
 params_end_tour:
  - 'ASC'
  - 'cons_2stops'
  - 'b_lnStops'
  - 'b_cost_return'
  - 'prob_return'
 params_next_stop:
  - 'b_LowDen'
  - 'b_Res'
  - 'b_Inter'
  - 'b_EmpNode'
  - 'b_same_ZIP'
  - 'b_cost_0'
  - 'b_cost_first'
  - 'b_cost_50'
  - 'b_jobs_pop'
 params_vehicle_generation:
  - 'A'
  - 'B'
  - 'C'
  - 'D'
  - 'E'
  - 'F'
  - 'G'
  - 'H (49-52)'
  - 'I'
  - 'J'
  - 'K'
  - 'L'
  - 'M'
  - 'N'
  - 'O'
  - 'P'
  - 'Q'
  - 'R'
  - 'S'
 zone_stats:
  - 'ID'
  - 'A'
  - 'B'
  - 'C'
  - 'D'
  - 'E'
  - 'F'
  - 'G'
  - 'H (49-52)'
  - 'I'
  - 'J'
  - 'K'
  - 'L'
  - 'M'
  - 'N'
  - 'O'
  - 'P'
  - 'Q'
  - 'R'
  - 'S'
  - 'Jobs'
  - 'Area'
  - 'Pop'
  - 'RoadAccessibility'

dimensions:
 branch:
  - 'A'
  - 'B'
  - 'C'
  - 'D'
  - 'E'
  - 'F'
  - 'G'
  - 'H (49-52)'
  - 'I'
  - 'J'
  - 'K'
  - 'L'
  - 'M'
  - 'N'
  - 'O'
  - 'P'
  - 'Q'
  - 'R'
  - 'S'
 vehicle_type: # this differentiation not used at the time, but we leave it as it might be useful later.
  - 'all'
 segment:
  - id: 'C'
    vehicle_type: [ 'all' ]
    branch: ['C']
  - id: 'F'
    vehicle_type: [ 'all' ]
    branch: [ 'F' ]
  - id: 'G'
    vehicle_type: [ 'all' ]
    branch: [ 'G' ]
  - id: 'H (49-52)'
    vehicle_type: [ 'all' ]
    branch: [ 'H (49-52)' ]
  - id: 'N'
    vehicle_type: [ 'all' ]
    branch: [ 'N' ]
  - id: 'Other'
    vehicle_type: [ 'all' ]
    branch: ['A', 'B', 'D', 'E', 'I', 'J', 'K', 'L', 'M', 'O', 'P', 'Q', 'R', 'S']

